
name: CoinGecko-Market
on:
  schedule:
    - cron: '*/5 * * * *'  # every five minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: npm install open
      - run: node /../../../../../dist/loadpage.js
