
name: CoinGecko-Market
on:
  schedule:
    - cron: '*/5 * * * *'  # every five minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: npm install open # module for opening windows
      - run: node loadpage.js # javascript for loading the page
        working-directory: .github/dist # set dist directory for script files
