
name: CoinGecko-Market
on:
  schedule:
    - cron: '*/5 * * * *'  # every five minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    steps:
      - uses: actions/checkout@v3
      run: npm ci
      - run: node dist/loadpage.js
