
name: CoinGecko-Market
    runs-on: ubuntu-latest
on:
  schedule:
    - cron: '*/5 * * * *'  # every five minutes
jobs:

    steps:
    - run:
       using: 'node16'
       main: 'dist/loadpage.js'
 
